### ISSUE TITLE
cannot connet to root@mysql

### ISSUE THREAD

**Issue by xiaoxinyi** [RedpointGames/phabricator#78]
I use `docker-compose` to setup `phabricator`.

```
 version: '2'
 services:
     phabricator:
           restart: always
           ports:
             - "62443:443"
             - "62080:80"
             - "62022:22"
           volumes:
             - ./phabricator/repos:/repos
             - ./phabricator/extensions:/srv/phabricator/phabricator/src/extensions
           depends_on:
             - mysql
           links:
             - mysql
           environment:
             - MYSQL_HOST=mysql
             - MYSQL_USER=root
             - MYSQL_PASS=phabricator
             - PHABRICATOR_REPOSITORY_PATH=/repos
             - PHABRICATOR_HOST=192.168.199.208
           image: redpointgames/phabricator
     mysql:
           restart: always
           volumes:
             - ./phabricator/mysql:/var/lib/mysql
           image: mysql:5.7.14
           environment:
             - MYSQL_ROOT_PASSWORD=phabricator
```

I use `docker-compose up` to setup the application. Error when connecting `mysql`

```
 Raw MySQL Error: Attempt to connect to root@mysql failed with error #2002:

...

mysqlcheck: Got error: 1049: Unknown database 'phabricator_search' when selecting the database
```
